### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by rafaelsantosmg** [traccar/traccar-web#1285]
**Describe the bug**

We are trying to integrate the front but this error persists whenever we try to run the front on the production server, always returning this error.

```
TypeError: Cannot read properties of null (reading 'useState')
    at useState (https://trackaero.cfs.app.br/node_modules/.vite/deps/chunk-OU5AQDZK.js?v=05b0d8da:124:86)
    at usePersistedState (https://trackaero.cfs.app.br/src/common/util/usePersistedState.js:1:361)
    at LocalizationProvider (https://trackaero.cfs.app.br/src/common/components/LocalizationProvider.jsx:226:35)
    at renderWithHooks (https://trackaero.cfs.app.br/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=084f0e11:11548:26)
    at mountIndeterminateComponent (https://trackaero.cfs.app.br/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=084f0e11:14926:21)
    at beginWork (https://trackaero.cfs.app.br/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=084f0e11:15914:22)
    at beginWork$1 (https://trackaero.cfs.app.br/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=084f0e11:19753:22)
    at performUnitOfWork (https://trackaero.cfs.app.br/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=084f0e11:19198:20)
    at workLoopSync (https://trackaero.cfs.app.br/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=084f0e11:19137:13)
    at renderRootSync (https://trackaero.cfs.app.br/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=084f0e11:19116:15)
```
    
 Running the application locally this does not happen.

**Comment by tananaev** [comment]
This doesn't look like production code. For discussion please use the forum instead.
