### ISSUE TITLE
Blank page on device info page

### ISSUE THREAD

**Issue by MaTyyyJ** [traccar/traccar-web#954]
**Describe the bug**
When I click on the details button on a device that displays in the map I get a blank table visible for a while, which suddenly disappears and errors appear in the console. The problem occurs on version 5.0 and on the latest branch masters (web and server)

**To Reproduce**
1. Click on device
2. Click details on device on map 
3. Got blank page without any data.

**Expected behavior**
I think it should display infromation about device.

**Screenshots**
![image](https://user-images.githubusercontent.com/13423730/171255537-fb010802-80ca-47d0-8ec2-b1d9e8a75a14.png)
![image](https://user-images.githubusercontent.com/13423730/171255402-5c247fa4-7d61-4036-98ae-f95db79599c3.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome 102
 - Traccar 5.0 
 - GT06 device protocol.

**Additional context**
```
Uncaught Error: Objects are not valid as a React child (found: object with keys {radioType, considerIp, cellTowers}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13231:1)
    at reconcileChildFibers (react-dom.development.js:14133:1)
    at reconcileChildren (react-dom.development.js:16990:1)
    at mountIndeterminateComponent (react-dom.development.js:17890:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
throwOnInvalidObjectType @ react-dom.development.js:13231
reconcileChildFibers @ react-dom.development.js:14133
reconcileChildren @ react-dom.development.js:16990
mountIndeterminateComponent @ react-dom.development.js:17890
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
(anonymous) @ PositionPage.js:53
await in (anonymous) (async)
(anonymous) @ reactHelper.js:18
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react-dom.development.js:20085 

The above error occurred in the <PositionValue> component:

    at PositionValue (http://192.168.100.7:3000/static/js/bundle.js:5320:5)
    at td
    at http://192.168.100.7:3000/static/js/bundle.js:25839:66
    at TableCell (http://192.168.100.7:3000/static/js/bundle.js:62797:83)
    at tr
    at http://192.168.100.7:3000/static/js/bundle.js:25839:66
    at TableRow (http://192.168.100.7:3000/static/js/bundle.js:63192:82)
    at tbody
    at http://192.168.100.7:3000/static/js/bundle.js:25839:66
    at TableBody (http://192.168.100.7:3000/static/js/bundle.js:62581:82)
    at table
    at http://192.168.100.7:3000/static/js/bundle.js:25839:66
    at Table (http://192.168.100.7:3000/static/js/bundle.js:62350:82)
    at div
    at http://192.168.100.7:3000/static/js/bundle.js:25839:66
    at Paper (http://192.168.100.7:3000/static/js/bundle.js:58104:82)
    at div
    at http://192.168.100.7:3000/static/js/bundle.js:25839:66
    at Container
    at div
    at div
    at PositionPage (http://192.168.100.7:3000/static/js/bundle.js:12193:19)
    at Outlet (http://192.168.100.7:3000/static/js/bundle.js:158238:26)
    at div
    at App (http://192.168.100.7:3000/static/js/bundle.js:1626:19)
    at Routes (http://192.168.100.7:3000/static/js/bundle.js:158330:5)
    at Navigation (http://192.168.100.7:3000/static/js/bundle.js:1941:82)
    at Router (http://192.168.100.7:3000/static/js/bundle.js:158263:15)
    at BrowserRouter (http://192.168.100.7:3000/static/js/bundle.js:157073:5)
    at InnerThemeProvider (http://192.168.100.7:3000/static/js/bundle.js:69199:70)
    at ThemeProvider (http://192.168.100.7:3000/static/js/bundle.js:67675:5)
    at ThemeProvider (http://192.168.100.7:3000/static/js/bundle.js:69219:5)
    at StyledEngineProvider (http://192.168.100.7:3000/static/js/bundle.js:67860:5)
    at LocalizationProvider (http://192.168.100.7:3000/static/js/bundle.js:4848:5)
    at Provider (http://192.168.100.7:3000/static/js/bundle.js:153275:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
(anonymous) @ PositionPage.js:53
await in (anonymous) (async)
(anonymous) @ reactHelper.js:18
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

**Comment by MaTyyyJ** [comment]
@tananaev I noticed that everything works properly when I have the ignition fired up.

**Comment by tananaev** [comment]
Your screenshot is definitely not the latest code. Are you sure you're properly clearing the cache after updates?

**Comment by MaTyyyJ** [comment]
@tananaev - yes im sure im in nevest version. unrelated to this functionality screenshot I took from the old version (because it appears on master and tag 5.0.0 and it was only about which button I click)

![image](https://user-images.githubusercontent.com/13423730/171262156-94df6af3-c943-48d0-aa2d-1b0b1a5541c2.png)

**Comment by tananaev** [comment]
Can you please provide JSON for the position that it crashes on.

**Comment by MaTyyyJ** [comment]
I updated last comment with network json
