### ISSUE TITLE
Device details blank for some devices in modern interface

### ISSUE THREAD

**Issue by MikaVilpo** [traccar/traccar-web#972]
**Describe the bug**
Some (in this case MT90) devices are returning white page when accessing details of device in modern interface. Other devices (in my case Teltonika and Traccar Client) are working just fine and displaying the details of the device.

**To Reproduce**
Login to modern interface
Select MT90 device
Click Info 

**Expected behavior**
Device details shown as in other devices.

**Screenshots**
![image](https://user-images.githubusercontent.com/44055222/175864554-9a7baf7e-c879-41d1-a69c-6b303ab21f40.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge + Chrome
 - Version  103.0.1264.37

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - OS: Android
 - Browser Chrome
 - Version 

**Additional context**
In database I can fetch location with ID 482430 (select * from tc_positions where id = 482430;)

**Console from Chrome:**
```
Failed to load resource: the server responded with a status of 404 (Not Found)
serviceWorker.js:85 Content is cached for offline use.
maplibre-gl.js:31 Image "-11" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.
O @ maplibre-gl.js:31
maplibre-gl.js:31 Image "convenience-11" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.
O @ maplibre-gl.js:31
react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BradioType%2C%20considerIp%2C%20cellTowers%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _o (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Ia (react-dom.production.min.js:176:171)
    at Us (react-dom.production.min.js:268:385)
    at Ol (react-dom.production.min.js:250:347)
    at xl (react-dom.production.min.js:250:278)
    at _l (react-dom.production.min.js:250:138)
    at pl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
os @ react-dom.production.min.js:216
482512:1          Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Console in Edge:**
```
react-dom.production.min.js:216 
        
       Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BradioType%2C%20considerIp%2C%20cellTowers%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _o (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Ia (react-dom.production.min.js:176:171)
    at Us (react-dom.production.min.js:268:385)
    at Ol (react-dom.production.min.js:250:347)
    at xl (react-dom.production.min.js:250:278)
    at _l (react-dom.production.min.js:250:138)
    at pl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
os @ react-dom.production.min.js:216
482430:1 
        

       Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by tananaev** [comment]
What version are you using? Have you tried master?

**Comment by MikaVilpo** [comment]
Using 5.0. Haven't tried from master compiling myself.

**Comment by tananaev** [comment]
This should already be fixed on master.
